<?php

return [
    'countries' => [
        'Brasil' => 'Brasil',
        'Argentina' => 'Argentina',
        'Bolívia' => 'Bolívia',
        'Chile' => 'Chile',
        'Colômbia' => 'Colômbia',
        'Equador' => 'Equador',
        'Paraguai' => 'Paraguai',
        'Peru' => 'Peru',
        'Uruguai' => 'Uruguai',
        'Venezuela' => 'Venezuela',
        'Portugal' => 'Portugal',
        'Espanha' => 'Espanha',
        'Estados Unidos' => 'Estados Unidos',
        'Outro' => 'Outro',
    ],

    'brazilian_states' => [
        'AC' => 'Acre',
        'AL' => 'Alagoas',
        'AP' => 'Amapá',
        'AM' => 'Amazonas',
        'BA' => 'Bahia',
        'CE' => 'Ceará',
        'DF' => 'Distrito Federal',
        'ES' => 'Espírito Santo',
        'GO' => 'Goiás',
        'MA' => 'Maranhão',
        'MT' => 'Mato Grosso',
        'MS' => 'Mato Grosso do Sul',
        'MG' => 'Minas Gerais',
        'PA' => 'Pará',
        'PB' => 'Paraíba',
        'PR' => 'Paraná',
        'PE' => 'Pernambuco',
        'PI' => 'Piauí',
        'RJ' => 'Rio de Janeiro',
        'RN' => 'Rio Grande do Norte',
        'RS' => 'Rio Grande do Sul',
        'RO' => 'Rondônia',
        'RR' => 'Roraima',
        'SC' => 'Santa Catarina',
        'SP' => 'São Paulo',
        'SE' => 'Sergipe',
        'TO' => 'Tocantins',
    ],
];
